project:
  type: website
  output-dir: docs

website:
  title: "Csenge + Lapo"
  navbar:
    background: transparent
    left:
      - text: Kezdőlap
        href: index.qmd
      - text: Helyszín
        href: location.qmd
      - text: Infó
        href: info.qmd
      - text: RSVP
        href: rsvp_hu.qmd

from: markdown+emoji

format:
  html:
    theme: 
    - cosmo
    - color.scss



